---
- name: debian | Adding Pre-Reqs
  apt:
    name:
      - gnupg2
      - apt-transport-https
    state: present
    update_cache: true
  become: true
  register: result
  until: result is successful

- name: debian | adding RabbitMQ public GPG key to the apt repo
  apt_key:
    url: "{{ rabbitmq_debian_repo_key }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | adding RabbitMQ repo
  apt_repository:
    repo: "{{ rabbitmq_debian_repo }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | add Rabbitmq erlang repo
  apt_repository:
    repo: deb https://dl.bintray.com/rabbitmq-erlang/debian {{ ansible_distribution_release }} erlang
    state: present
  become: true
  when: rabbitmq_debian_erlang_from_rabbit

- name: debian | installing RabbitMQ server
  apt:
    name:
      - rabbitmq-server{{ (rabbitmq_debian_version_defined and rabbitmq_debian_version is defined) | ternary(['=',rabbitmq_debian_version] | join(''),'') }}
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | ensuring that the RabbitMQ service is running
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
  become: true
